Added a command "quick select bookmark from active group"
tommyme/vscode-bookmark-x pull request #10
Opened 2024-08-19 17:31 UTC by DragosStefanNecula

This works as expected + I also added some code that accounts for an edge case (no bookmarks are available). Thank you for letting me make contribution to your extension! Hope you have a nice day. (Let me know if there is anything to fix in my code).

Related to issue #8 

Also by the way, when I ran the code the first time there was a bug in compiling I haven't solved.

2024-08-20 12:01 UTC, tommyme requested changes
there is a small problem, seems good generally.

2024-08-20 12:01 UTC, tommyme commented on src/views/bookmark_x/controller.ts
> +        } else {
`Else` here is redundant and remove it can reduce the level of indentation.

2024-08-20 18:07 UTC, DragosStefanNecula commented
Thank you!, I have changed the code as you requested

2024-08-21 07:15 UTC, tommyme reviewed
Thank you for your contribution! new beta version will be published in a week.

2024-08-21 07:18 UTC, merged