feat: Add manual sort support
tommyme/vscode-bookmark-x pull request #11
Opened 2024-08-21 10:15 UTC by Latria-Kure

A new treeitem inline icon te select/deselect sort item. 
Two arrow icon at view/title/navigation to move the selected sort item. 
Add group command is also moved to the same place to make it more convenient.

icon to select:
![image](https://github.com/user-attachments/assets/b4953adf-922e-40cd-b660-c2466ce1c23e)

icon to deselect:
![image](https://github.com/user-attachments/assets/5257ebe1-073e-46e9-9996-19cc031a19e4)

A 'manual' option is added to settings to enable/disable manual sort.
![image](https://github.com/user-attachments/assets/7d5d8424-7d85-45c9-85f0-0b718b4e0671)

The sort action support all type of treeitem(bookmark/group/groupbookmark).

2024-08-21 14:00 UTC, tommyme requested changes
A cool feature, thank you for reading the source code and contributing to it!

2024-08-22 01:25 UTC, Latria-Kure commented on src/views/bookmark_x/controller.ts
> +    static get sorting_node() {
No. Because this is my first pr and I'm new to use typescript to write extension. I meet getter and setter first and I think it is cool :)

2024-08-22 01:34 UTC, Latria-Kure commented on src/views/bookmark_x/constants.ts
> +export const ICON_ACTIVE_GROUP = new ThemeIcon("folder-opened", new ThemeColor("bookmark_x.activeGroupColor"));
The default value is set to `statusBarItem.remoteBackground` in contributes.jsonc now.

2024-08-22 02:38 UTC, tommyme approved these changes
Cool, it'll be published to beta version later, Thanks for contributing❤️

2024-08-22 14:11 UTC, merged

2024-08-23 15:16 UTC, tommyme commented
There is a problem when more than one projects are opened. 
because rg is different, `vicache.get` will fail.
![image](https://github.com/user-attachments/assets/a08e4f31-7aeb-4822-916f-1226ff288e94)

do you have some idea to fix it in a elelegant way?

2024-08-23 15:23 UTC, tommyme commented
It can be trigged like this.
![test (2)](https://github.com/user-attachments/assets/95885266-477a-469e-befa-a8644efeae87)