feat: Support icon change when sorting
tommyme/vscode-bookmark-x pull request #15
Opened 2024-08-26 06:57 UTC by Latria-Kure

When activating/deactivating a group, if a parent group of the active group is sorting, the parent group will keep using sorting icon.
![sorting_icon_change](https://github.com/user-attachments/assets/59b459c6-165f-46d7-aafa-7cd41bd0c072)

2024-08-26 15:00 UTC, tommyme commented
During working days, merging pull requests may be slightly delayed.

2024-08-27 13:52 UTC, tommyme requested changes
consider adding a class to do the dirty thing, make it more graceful.

2024-08-27 13:52 UTC, tommyme commented on src/views/bookmark_x/controller.ts
> +import { ICON_BOOKMARK, ICON_ACTIVE_GROUP, ICON_GROUP, ICON_SORTING_BOOKMARK, ICON_SORTING_ACTIVE_GROUP, ICON_SORTING_GROUP } from "./constants"
merge the line with line 17

2024-08-27 13:52 UTC, tommyme commented on src/views/bookmark_x/bookmark_tree_view.ts
> +                if (ITEM_TYPE_GROUP_LIKE.includes(tvi.base!.type)) {
use `typeIsGroupLike` in constants.ts instead

2024-08-27 13:52 UTC, tommyme commented on src/views/bookmark_x/controller.ts
> +        if (ITEM_TYPE_GROUP_LIKE.includes(item.base!.type)) {
use typeIsGroupLike in constants.ts instead

2024-08-27 13:52 UTC, tommyme commented on src/views/bookmark_x/controller.ts
> +            }
add a class to do the dirty thing.
In principle, if this function can be done outside the Controller, don't do it in the Controller.

2024-08-27 13:52 UTC, tommyme commented on src/views/bookmark_x/controller.ts
> +        }
add a class to do the dirty thing.

2024-08-27 13:52 UTC, tommyme commented on src/views/bookmark_x/controller.ts
> +                );
what kind of formatter r u using, I'll set a formatter for the project later, but now, if it is not a serious formatting problem, you can ignore it for now

Except for the above formatting changes, all others are reasonable.

currently, I'm using 
![image](https://github.com/user-attachments/assets/a714090f-587a-4ab9-8584-b791371aa2b8)

2024-08-27 13:52 UTC, tommyme commented on src/views/bookmark_x/functional_types.ts
>              if (ITEM_TYPE_GROUP_LIKE.includes(tvi.base!.type)) {
here I should use typeIsGroupLike in constants.ts instead.

2024-08-27 13:52 UTC, tommyme commented on src/views/bookmark_x/functional_types.ts
> +            }
I think the tvi icon updateing here can be rewrite, some logic can be merged into a class like e.g. `TviIconManager` 

call it's method and refresh the icon.

there may be some difficulty to get infos from controller.

2024-08-27 13:53 UTC, tommyme commented
Before committing, please use command `npx eslint **/*.ts` to check errors.

2024-08-27 23:42 UTC, Latria-Kure commented
> consider adding a class to do the dirty thing, make it more graceful.

Thanks for your advice. I am new to js and ts. So thank you very much for pointing out my mistake, especially regarding the design of the program.

2024-08-30 14:32 UTC, merged

2024-08-30 14:42 UTC, tommyme commented
According to your idea, I realized this feat

2024-08-31 00:27 UTC, Latria-Kure commented
> According to your idea, I realized this feat

Sorry, I’ve been out for the past few days. I will submit a refactor PR shortly.

2024-08-31 02:21 UTC, Latria-Kure commented
I just found the refactoring has finished. Thanks!